apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myistiogateway
  namespace: istio-test
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapimapping
  namespace: istio-test
spec:
  hosts:
  - sanjayjanarthanan.click
  gateways:
  - myistiogateway
  http:
  - match:
    - uri:
        prefix: "/users"
    route:
    - destination:
        host: dotnet6webapiservice
        port:
          number: 80
      weight: 100
  - match:
    - uri:
        prefix: "/health"
    route:
    - destination:
        host: dotnet6webapiservice
        port:
          number: 80
      weight: 100
---
